[general]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "Agave Nerd Font Propo"
style = "Regular"

[font.bold_italic]
family = "Agave Nerd Font Propo"
style = "Regular"

[font.italic]
family = "Agave Nerd Font Propo"
style = "Regular"

[font.normal]
family = "Agave Nerd Font Propo"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 500
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false

[window.padding]
x = 5
y = 5


# https://github.com/tinted-theming/tinted-terminal/tree/main/themes/alacritty


# Default colors
[colors.primary]
background = '#191919'
foreground = '#cacaca'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#393939'
cursor = '#e7e7e7'

# Normal colors
[colors.normal]
black = '#0f0f0f'
red = '#ac8a8c'
green = '#8aac8b'
yellow = '#ceb188'
blue = '#8aabac'
magenta = '#8f8aac'
cyan = '#ac8aac'
white = '#cacaca'

# Bright colors
[colors.bright]
black = '#4c4c4c'
red = '#ac8a8c'
green = '#8aac8b'
yellow = '#ceb188'
blue = '#8aabac'
magenta = '#8f8aac'
cyan = '#ac8aac'
white = '#f0f0f0'
