[general]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "Agave Nerd Font Propo"
style = "Regular"

[font.bold_italic]
family = "Agave Nerd Font Propo"
style = "Regular"

[font.italic]
family = "Agave Nerd Font Propo"
style = "Regular"

[font.normal]
family = "Agave Nerd Font Propo"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 500
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false

[window.padding]
x = 5
y = 5


# https://github.com/tinted-theming/tinted-terminal/tree/main/themes/alacritty


# Default colors
[colors.primary]
background = '#1f1f28'
foreground = '#dcd7ba'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#dcd7ba'
cursor = '#717c7c'

# Normal colors
[colors.normal]
black = '#1f1f28'
red = '#c34043'
green = '#76946a'
yellow = '#c0a36e'
blue = '#7e9cd8'
magenta = '#6a9589'
cyan = '#957fb8'
white = '#c8c093'

# Bright colors
[colors.bright]
black = '#16161d'
red = '#c34043'
green = '#76946a'
yellow = '#c0a36e'
blue = '#7e9cd8'
magenta = '#6a9589'
cyan = '#957fb8'
white = '#dcd7ba'
