shadow = true;
shadow-radius = 10;
shadow-opacity = .70
shadow-offset-x = 0;
shadow-offset-y = 0;
fading = true;
fade-in-step = .15;
fade-out-step = .15;
fade-delta = 5;
no-fading-openclose = false;
no-fading-destroyed-argb = false;
frame-opacity = 1;
inactive-dim-fixed = false;
corner-radius = 0;
blur-background = false;
blur-background-frame = false
blur-kern = "5x5gaussian";
dbus = false;
daemon = false;
backend = "xrender";
vsync = true; #
detect-rounded-corners = false;
detect-client-opacity = true; #
use-ewmh-active-win = false;
unredir-if-possible = false;
detect-transient = true; #
use-damage = true; #
force-win-blend = true;
no-ewmh-fullscreen = false;
max-brightness = 1;
transparent-clipping = false;

rules: (
    {
        match = "window_type = 'tooltip'";
        fade = false;
        shadow = false;
        opacity = .75;
        full-shadow = false;
    },
    {
        match = "window_type = 'dock' || window_type = 'desktop'";
        corner-radius = 0;
    },
    {
        match = "class_g = 'Dunst'";
        shadow = false;
        opacity = .8;
        transparent-clipping = true;
    },
    {
        match = "class_g = 'Alacritty'";
        opacity = .95;
        transparent-clipping = true;
    },
    {
        match = "window_type = 'popup_menu' || window_type = 'dropdown_menu' || window_type = 'menu'";
        opacity = 1;
        shadow = false;
        transparent-clipping = false;
    },
    {
        match = "class_g = 'i3bar'";
        opacity = .95;
        shadow = true;
    },
    {
        match = "class_g = 'Rofi'";
        opacity = .9;
        transparent-clipping = false;
    },
    {
        match = "_NET_WM_STATE@[*] = '_NET_WM_STATE_MAXIMIZED_HORZ' && _NET_WM_STATE@[*] = '_NET_WM_STATE_MAXIMIZED_VERT'";
        shadow = false;
    }
)
