[colors]
base00 = #181616
base01 = #282727
base02 = #393836
base03 = #625e5a
base04 = #737c73
base05 = #c5c9c5
base06 = #c8c093
base07 = #c5c9c5
base08 = #c4746e
base09 = #b6927b
base0A = #c4b28a
base0B = #8a9a7b
base0C = #8ea4a2
base0D = #8ba4b0
base0E = #a292a3
base0F = #b98d7b
[settings]
screenchange-reload = true
pseudo-transparency = false
format-foreground =
format-background =
format-underline =
format-overline =
format-spacing =
format-padding =
format-margin =
format-offset =
[barbase]
monitor-strict = true
monitor-exact = false
override-redirect = true
fixed-center = true
width = 99%
offset-x = 0.5%
offset-y = 0.5%
background = ${colors.base01}
foreground = ${colors.base07}
line-size = 0
line-color = ${colors.base08}
radius = 0.0
border-size = 1pt
border-color = ${colors.base03}
module-margin = 5pt
font-0 = VictorMono Nerd Font:style=Bold:size=9; 2
font-1 = Noto Color Emoji:style=Regular:scale=10:size=9; 2
font-2 = Noto Sans Symbols:style=Regular; 2
font-3 = Symbols Nerd Font:style=Regular; 2
font-4 = Font Awesome 7 Free:style=Regular; 2
padding = 10pt
separator = |
dim-value = 0.0
wm-name = i3
locale = en_US.UTF-8
enable-struts = true
dpi = 0
enable-ipc = false
click-left =
click-middle =
click-right =
scroll-up = "#i3.prev"
scroll-down = "#i3.next"
double-click-left =
double-click-middle =
double-click-right =
double-click-interval = 400
cursor-click =
cursor-scroll =
wm-restack = i3
[dummybarbase]
monitor-strict = true
monitor-exact = false
override-redirect = false
background = #00000000
padding = 0
modules-left = emptymodule
modules-center = emptymodule
modules-right = emptymodule
[bar/dummytop]
inherit = dummybarbase
monitor = ${env:MONITOR:}
height = 18pt
bottom = false
[bar/top]
inherit = barbase
monitor = ${env:MONITOR:}
height = 16pt
modules-left = empty
modules-center = backlightmodule pulseaudiomodule batterymodule xkeyboardmodule wirednetworkmodule wirelessnetworkmodule traymodule
modules-right = empty
bottom = false
[bar/dummybottom]
inherit = dummybarbase
monitor = ${env:MONITOR:}
height = 18pt
bottom = true
[bar/bottom]
inherit = barbase
monitor = ${env:MONITOR:}
height = 16pt
modules-left = empty
modules-center = temperaturemodule cpumodule memorymodule i3module datemodule filesystemmoduleroot filesystemmodulehome
modules-right = empty
bottom = true
[global/wm]
margin-bottom = 10pt
margin-top = 10pt
[module/emptymodule]
type = custom/text
content = " "
[module/traymodule]
type = internal/tray
tray-spacing = 2pt
tray-padding =
tray-size = 50%
; tray-background =
; tray-foreground =
[module/i3module]
type = internal/i3
ws-icon-0 = "1;"
ws-icon-1 = "2;󰖟"
ws-icon-2 = "3;󰅴"
ws-icon-3 = "4;"
ws-icon-4 = "5;"
ws-icon-default =
pin-workspaces = true
show-urgent = true
strip-wsnumbers = false
index-sort = false
enable-click = true
enable-scroll = false
wrapping-scroll = false
reverse-scroll = false
format = <label-state> <label-mode>
label-mode = %mode%
label-mode-padding = 2
label-mode-background = ${colors.base08}
label-mode-foreground = ${colors.base00}
label-mode-underline =
label-focused = "%icon%"
label-focused-foreground = ${colors.base00}
label-focused-background = ${colors.base0D}
label-focused-underline =
label-focused-padding = 2
label-unfocused-foreground = ${colors.base07}
label-unfocused-background = ${colors.base01}
label-unfocused-underline =
label-unfocused = "%icon%"
label-unfocused-padding = 2
label-visible-foreground = ${colors.base07}
label-visible-background = ${colors.base02}
label-visible-underline =
label-visible = "%icon%"
label-visible-padding = 2
label-urgent-foreground = ${colors.base00}
label-urgent-background = ${colors.base08}
label-urgent-underline =
label-urgent = %icon%
label-urgent-padding = 2
label-separator = |
label-separator-padding = 1
label-separator-foreground = ${colors.base06}
[module/backlightmodule]
type = internal/backlight
card = intel_backlight
use-actual-brightness = true
poll-interval = 0
enable-scroll = false
scroll-interval =
format = <ramp>  <label>
label = %percentage%%
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 
bar-width =
bar-indicator =
bar-fill =
bar-empty =
[module/pulseaudiomodule]
type = internal/pulseaudio
; Sink to be used, if it exists (find using `pacmd list-sinks`, name field)
; If not, uses default sink
; sink = alsa_output.pci-0000_12_00.3.analog-stereo
use-ui-max = true
interval = 5
reverse-scroll = false
format-volume = <ramp-volume>  <label-volume>
format-muted = "<label-muted>"
label-volume = %percentage%%
label-muted =   %percentage%%
label-muted-foreground = ${colors.base08}
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
click-right =
[module/batterymodule]
type = internal/battery
full-at = 99
low-at = 5
; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = AC0
poll-interval = 5
time-format = %H:%M
format-charging = <animation-charging>  <label-charging>
format-discharging = <ramp-capacity>  <label-discharging>
format-full = <ramp-capacity>  <label-full>
format-low = <animation-low>  <label-low>
label-charging = %percentage%% %time%
label-discharging = %percentage%% %time%
label-full = %percentage%%
label-low = %percentage%%
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
bar-capacity-width =
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750
animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
animation-discharging-framerate = 500
animation-low-0 = !
animation-low-1 =
animation-low-framerate = 200
[module/cpumodule]
type = internal/cpu
interval = 0.5
warn-percentage = 95
format = <label>
format-warn = <label-warn>
label =   %percentage%%
label-warn =   %percentage%%
ramp-coreload-spacing = 1
ramp-coreload-0 =
ramp-coreload-1 =
ramp-coreload-2 =
ramp-coreload-3 =
ramp-coreload-4 =
ramp-coreload-5 =
ramp-coreload-6 =
ramp-coreload-7 =
[module/datemodule]
type = internal/date
interval = 30
date = %Y-%m-%d
time = %H:%M
; date-alt =
; time-alt =
format = <label>
label = "   %date% 󰟛 %time% "
format-background = ${colors.base0B}
format-foreground = ${colors.base00}
[filesystembase]
type = internal/fs
interval = 10
fixed-values = false
spacing = 2
warn-percentage = 85
format-mounted = <label-mounted>
format-unmounted = <label-unmounted>
format-warn = <label-warn>
label-mounted = 󰋊 %mountpoint% %used% / %total%
label-unmounted = 󱁌 %mountpoint%
label-warn = 󱁋 %mountpoint% %percentage_used%%
[module/filesystemmoduleroot]
inherit = filesystembase
mount-0 = /
[module/filesystemmodulehome]
inherit = filesystembase
mount-0 = /home
[networkbase]
type = internal/network
interval = 5.0
accumulate-stats = false
speed-unit="B/s"
format-disconnected = <label-disconnected>
format-packetloss = <animation-packetloss> <label-connected>
label-connected-foreground = ${colors.base0B}
animation-packetloss-0 = 
animation-packetloss-0-foreground = ${colors.base09}
animation-packetloss-1 = 
animation-packetloss-1-foreground = ${colors.base0A}
animation-packetloss-framerate = 500
label-disconnected-foreground = ${colors.base08}
[module/wirednetworkmodule]
type = internal/network
interface = eno2
interface-type = wired
label-connected =   %ifname%: %local_ip% 󰾅  %netspeed%
format-connected = <label-connected>
label-disconnected = 󰈁 (%ifname%)
[module/wirelessnetworkmodule]
type = internal/network
interface = wlan0
interface-type = wireless
label-connected = %essid% (%ifname%: %local_ip%) 󰾅  %netspeed%
format-connected = <ramp-signal>  <label-connected>
label-disconnected = 󰤮  (%ifname%)
label-disconnected-foreground =
ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨
ramp-signal-5 = 󰤨
[module/temperaturemodule]
type = internal/temperature
interval = 2
thermal-zone = 0
zone-type = x86_pkg_temp
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon6/temp1_input
base-temperature = 0
warn-temperature = 80
units = true
format = <ramp> <label>
format-warn = <ramp> <label-warn>
label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.base08}
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.base09}
[module/memorymodule]
type = internal/memory
interval = 3
warn-percentage = 90
format = <label>
format-warn = <label-warn>
label =   %used% / %total%
label-warn =   %used% / %total%
bar-used-indicator =
bar-used-width = 50
; bar-used-foreground-0 =
; bar-used-foreground-1 =
; bar-used-foreground-2 =
; bar-used-foreground-3 =
; bar-used-fill =
; bar-used-empty =
; bar-used-empty-foreground =
; ramp-used-0 =
; ramp-used-1 =
; ramp-used-2 =
; ramp-used-3 =
; ramp-used-4 =
; ramp-used-5 =
; ramp-used-6 =
; ramp-used-7 =
; ramp-free-0 =
; ramp-free-1 =
; ramp-free-2 =
; ramp-free-3 =
; ramp-free-4 =
; ramp-free-5 =
; ramp-free-6 =
; ramp-free-7 =
[module/xkeyboardmodule]
type = internal/xkeyboard
label-layout = "   %name% "
label-indicator-on = "%icon% "
label-layout-background = ${colors.base07}
label-layout-foreground = ${colors.base00}
indicator-icon-0 = caps lock;-CL;󰪛
indicator-icon-1 = scroll lock;;+SL
indicator-icon-2 = num lock;-NL;+NL
