[UPower]
EnableWattsUpPro=false
NoPollBatteries=false
IgnoreLid=false
UsePercentageForPolicy=true
PercentageLow=20.0
PercentageCritical=15.0
PercentageAction=10.0
TimeLow=1200
TimeCritical=300
TimeAction=120
ExpectBatteryRecalibration=false
AllowRiskyCriticalPowerAction=true
CriticalPowerAction=Suspend
# PowerOff
# Hibernate
# HybridSleep
# Auto (The CriticalPowerAction will be determined by the system)
# Suspend (AllowRiskyCriticalPowerAction should be true to use this option but risky)
# Ignore (AllowRiskyCriticalPowerAction should be true to use this option but risky)
