require("cfgpkg.builtins")
require("cfgpkg.fzfcfg")
require("cfgpkg.uicfg")
require("cfgpkg.coccfg")
require("cfgpkg.alphacfg")
require("cfgpkg.dapcfg")
require("cfgpkg.indentblanklinecfg")
require("cfgpkg.treesittercfg")
