require('cfgpkg.builtins')
require('cfgpkg.fzfcfg')
require('cfgpkg.uicfg')
require('cfgpkg.lspcfg')
require('cfgpkg.alphacfg')
require('cfgpkg.dapcfg')
require('cfgpkg.indentblanklinecfg')
require('cfgpkg.treesittercfg')
