require('cfgpkg.builtins')
-- require('cfgpkg.fzfcfg')
require('cfgpkg.uicfg')
require('cfgpkg.lspcfg')
require('cfgpkg.dapcfg')
require('cfgpkg.treesittercfg')
require('cfgpkg.movecfg')
require('cfgpkg.pairscfg')
require('cfgpkg.trailspacecfg')
require('cfgpkg.splitcfg')
require('cfgpkg.pickcfg')
require('cfgpkg.startercfg')
